### ISSUE TITLE
Unobserve callbacks are not the observe callbacks

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/sightglass#10]
The update callback is wrapped with the bind(this) method (ecmascript 5). You call .bind(this) each time you send the bound callback as parameter. Unfortunately, all the bound callbacks will be different as the bind function recreates a function each time.
So the adapter will be unable to unreference the callbacks and we have a memory leak. See issue #430 in rivets (https://github.com/mikeric/rivets/issues/430)

My opinion : don't use .bind(this) as it is not available in all browsers (especially older androids). Use instead the good old "var self = this" method.

**Comment by JeffSwenson** [comment]
If you implement an adapter using Object.observe and Object.unobserve, then this bug combines with a [V8 bug](https://code.google.com/p/v8/issues/detail?id=4324) to cause exceptions.
