### ISSUE TITLE
Error when running under phantomJS

### ISSUE THREAD

**Issue by jlallement** [mikeric/sightglass#9]
When running under phantomJS, sightglass throw an exception at line 88 :

    this.set(true, token, current, this.update.bind(this))

phantom log this message :

    this.update.bind is undefined

**Comment by Zertz** [comment]
This is because Phantom < 2 uses an old build of WebKit. Simply inject [es5-shim](https://github.com/es-shims/es5-shim) into Phantom or include it on your page.

**Comment by rposborne** [comment]
Can confirm that this can be resolved with es5-shim. 

``` ruby
# Gemfile
source 'https://rails-assets.org' do
  gem 'rails-assets-es5-shim'
end

# application.js 
# es5-shim must be required prior to sightglass 
//= require es5-shim
//= require sightglass
```

Think this issue can be closed.
